DROP TABLE IF EXISTS ACCESS;


CREATE TABLE ACCESS (
	COURSENAME VARCHAR(255),
	COURSELINK VARCHAR(255) NOT NULL,
	SUB VARCHAR(255) NOT NULL,
	PRIMARY KEY(SUB, COURSELINK)
);

DROP TABLE IF EXISTS moodle_lrs_mapping;

CREATE TABLE moodle_lrs_mapping (
  moodle_token varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  PRIMARY KEY (email)
)
